site_name: My Docs
theme:
  name: material
  palette:
    primary: "blue"
    accent: "orange"
  font:
    text: "Ubuntu"
repo_name: Kludex/starlette-testclient
repo_url: https://github.com/Kludex/starlette-testclient

nav:
  - Home: index.md

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - tables
  - smarty
  - pymdownx.tabbed
